#!/usr/bin/env python3
"""Generate expected_asym_nudged.h for UnitTestTensorConversion (group-quant
PR4 Task 1, spec D6).

Emulates the NUDGED CODE-DOMAIN ASYM quantizer (deriveAsymGridFromMinMax +
emitAsymChunk after the PR4 rewrite) BIT-EXACTLY in float32 -- see
sym_gold.quantize_asym_nudged for the math and its inline self-checks
(zp in [0, 2^b-1], exact-zero decode, 0.5*scale round-trip bound).

This is a DELIBERATE numerics change (D6): existing ASYM pins re-derive
through the new math, they are NOT sign-flips of the old codes. Every fixture
below therefore also runs the OLD value-domain emulation
(quantize_asym_old_value_domain) and asserts old != new on at least one of
{codes, zp} -- a generator run that cannot distinguish the two grids aborts
instead of emitting vacuous pins.

Fixtures:
  f1SpanZero   {1,2,3,4,-1,-2} @ qBits=5 -- the canonical 6-element pin
               (testConversionFloatAsym / IntAsym / SymInt32Asym). Band spans
               zero, nudge is a no-op; zp flips -10 -> +10 and the codes
               happen to coincide with the old grid (verified, not assumed).
  f2NegBand16  {-10,-1,-5.5,-2.5,-9.25,-3.75} @ qBits=16 -- all-negative
               band; the nudge extends it to [-10, 0] so zp lands exactly on
               the uint16 ceiling 2^16-1 = 65535 (the D6 boundary pin that
               replaces the old -72817 int32-width pin).
  f3NegFar     {-5000000, -4999999.5} @ qBits=8 -- the old
               ZeroPointBeyondInt32 DEATH data: un-nudged zpReal ~ -2.55e9
               was an int32-overflow abort; nudged it derives a VALID grid
               (zp = 255). Pins the death-test obsolescence.
  f4ClampTie   {-1.5, 5.5, 0.0, 2.0} @ qBits=3, scale exactly 1.0 -- zpReal
               = 1.5 is an exact tie (zp -> 2) AND v=5.5 rounds up too, so
               the un-clamped top code is 8 > qMax=7: the ONE fixture whose
               emitted code needs the encode clamp (mutation (ii) guard).
               Also contains an exact 0.0 (zero-representability pin).
  f5SymDeq     {5,-4,2,-1,3,-5} @ qBits=5 -- the SYM->ASYM re-pin
               (testConversionSymToAsymRoundTrips' dequantized mantissas).
  f6AccumRef   {3, 2.5, 6, 5.25} @ qBits=5 -- the ASYM accumulate re-pin
               (testAccumulateAsymRescaleMatchesFloatReference's
               decode+increment reference); all-positive band, so the nudge
               is LIVE here: scale 3.5/31 -> 6/31, zp 22 -> 0.

Run via `uv run` (CMake wires this automatically).
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "goldgen"))

from sym_gold import (emit_float_array, emit_float_scalar, emit_int32_array,
                      emit_int32_scalar, quantize_asym_nudged,
                      quantize_asym_old_value_domain)

FIXTURES = [
    ("f1SpanZero", [1.0, 2.0, 3.0, 4.0, -1.0, -2.0], 5),
    ("f2NegBand16", [-10.0, -1.0, -5.5, -2.5, -9.25, -3.75], 16),
    ("f3NegFar", [-5000000.0, -4999999.5], 8),
    ("f4ClampTie", [-1.5, 5.5, 0.0, 2.0], 3),
    ("f5SymDeq", [5.0, -4.0, 2.0, -1.0, 3.0, -5.0], 5),
    ("f6AccumRef", [3.0, 2.5, 6.0, 5.25], 5),
]


def emit_fixture(parts, name, values, q_bits):
    codes, scale, zp = quantize_asym_nudged(values, q_bits)
    old_codes, _old_scale, old_zp = quantize_asym_old_value_domain(values, q_bits)
    assert (codes != old_codes) or (zp != old_zp), (
        f"{name}: nudged grid is indistinguishable from the old value-domain "
        f"grid -- pin would be vacuous (codes {codes}, zp {zp})")
    pre = f"asym_nudged_{name}"
    parts.append(emit_float_array(f"input_{pre}", __import__("torch").tensor(values)))
    parts.append(emit_int32_array(f"codes_{pre}", __import__("torch").tensor(codes, dtype=__import__("torch").int32)))
    parts.append(emit_float_scalar(f"scale_{pre}", scale))
    parts.append(emit_int32_scalar(f"zp_{pre}", zp))
    parts.append(emit_int32_scalar(f"qBits_{pre}", q_bits))
    return codes, scale, zp


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    parts = [
        "// AUTOGENERATED by generate_expected_asym_nudged.py — DO NOT EDIT\n",
        "#ifndef ODT_EXPECTED_ASYM_NUDGED_H\n",
        "#define ODT_EXPECTED_ASYM_NUDGED_H\n",
        "#include <stdint.h>\n",
        "#include <stdlib.h>\n\n",
    ]

    results = {}
    for name, values, q_bits in FIXTURES:
        results[name] = emit_fixture(parts, name, values, q_bits)

    # -- cross-fixture self-checks (see module docstring) --
    codes, scale, zp = results["f1SpanZero"]
    assert zp == 10 and codes == [15, 20, 26, 31, 5, 0], (
        f"f1SpanZero drifted from the hand derivation: codes {codes}, zp {zp}")
    _codes2, _scale2, zp2 = results["f2NegBand16"]
    assert zp2 == 2 ** 16 - 1, f"f2NegBand16: zp {zp2} != uint16 ceiling 65535"
    assert _codes2[0] == 0, f"f2NegBand16: min value must land on code 0, got {_codes2[0]}"
    codes3, _scale3, zp3 = results["f3NegFar"]
    assert zp3 == 255, f"f3NegFar: zp {zp3} != 255"
    codes4, scale4, zp4 = results["f4ClampTie"]
    assert scale4 == 1.0 and zp4 == 2, f"f4ClampTie: scale {scale4}, zp {zp4}"
    # the clamp must actually FIRE for v=5.5: un-clamped code is 6 + 2 = 8 > 7
    assert codes4[1] == 7, f"f4ClampTie: clamped top code {codes4[1]} != 7"
    from sym_gold import round_half_away
    import torch
    unclamped = int(round_half_away(torch.tensor(5.5 / scale4, dtype=torch.float32)).item()) + zp4
    assert unclamped == 8, (
        f"f4ClampTie: un-clamped top code {unclamped} != 8 -- fixture no "
        f"longer exercises the encode clamp (mutation (ii) guard vacuous)")
    assert codes4[2] == zp4, "f4ClampTie: 0.0 must encode to code == zp"

    parts.append("\n#endif // ODT_EXPECTED_ASYM_NUDGED_H\n")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
