#!/usr/bin/env python3
"""Generate expected_bfp_dropout.h for UnitTestDropout's BFP float-bridge test
(BFP epic PR4, R-P3 -- spec docs/superpowers/specs/2026-07-29-block-floating-
point-design.md, D4 "Dropout non-native BY DECISION" + deviations register 5).

Fixture design (each choice is a mutation the test must kill):
  - two groups of four with DIFFERENT stored exponents (130 / 126), so a
    per-tensor collapse or a dropped per-group walk is observable;
  - keep-even mask (UnitTestDropout's stubKeepEven), so masking is
    load-bearing and reproducible without touching the RNG;
  - p = 0.5 -> factor exactly 2.0: the bridge is EXACT, so the C side can be
    compared code-for-code, and the fixture is still non-trivial because
    group 1's masked absmax crosses a binade (stored 126 -> 128) while group
    0's does not (stored 130 -> 130) -- one moving and one static exponent in
    the same fixture.
Run via `uv run` (CMake wires this automatically, see CMakeLists.txt)."""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "goldgen"))

from sym_gold import (assert_rounding_canary, bfp_dequant_f32, bfp_mask_scale_repack_ref,
                      check_exact_roundtrip, emit_int32_array, emit_int32_scalar,
                      emit_uint8_array)

MANTISSA_BITS = 6
EXPONENT_BITS = 8
NUM_GROUPS = 2
GROUP_SIZE = 4
IN_CODES = [12, -7, 0, 31, -32, 5, -1, 20]
IN_EXPS = [130, 126]
KEEP_MASK = [i % 2 == 0 for i in range(8)]  # UnitTestDropout's stubKeepEven
FACTOR = 2.0  # 1 / (1 - 0.5)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    assert_rounding_canary()

    qc = {"mantissa_bits": MANTISSA_BITS, "exponent_bits": EXPONENT_BITS,
          "group_size": GROUP_SIZE}
    # R-P7b exact-regime pin: the fixture must be CANONICAL -- its exact
    # dequant must reproduce these codes under these exponents -- or the C
    # side's packed payload and the gold would describe different numbers.
    deq = bfp_dequant_f32(IN_CODES, IN_EXPS, qc)
    check_exact_roundtrip("bfp dropout input", [float(v) for v in deq],
                          IN_CODES, IN_EXPS, qc)
    out_codes, out_exps = bfp_mask_scale_repack_ref(IN_CODES, IN_EXPS, qc, KEEP_MASK, FACTOR)

    import torch
    body = [
        "/* GENERATED by generate_expected_bfp_dropout.py -- do not edit. */\n",
        "#include <stddef.h>\n#include <stdint.h>\n\n",
        emit_int32_scalar("kBfpDropoutMantissaBits", MANTISSA_BITS),
        emit_int32_scalar("kBfpDropoutExponentBits", EXPONENT_BITS),
        emit_int32_scalar("kBfpDropoutNumGroups", NUM_GROUPS),
        emit_int32_scalar("kBfpDropoutGroupSize", GROUP_SIZE),
        emit_int32_array("kBfpDropoutInCodes", torch.tensor(IN_CODES)),
        emit_uint8_array("kBfpDropoutInExps", IN_EXPS),
        emit_int32_array("kBfpDropoutOutCodes", torch.tensor(out_codes)),
        emit_uint8_array("kBfpDropoutOutExps", out_exps),
    ]
    Path(args.out).write_text("".join(body))


if __name__ == "__main__":
    main()
