#!/usr/bin/env python3
"""Generate expected_groupnorm.h for UnitTestGroupNorm (FLOAT32).

Emits PyTorch-derived ground truth: forward output y, propLoss dx, and the
parameter grads dgamma/dbeta, for four (B, C, T, G) fixtures covering G=1,
G>1, batch>1 and the G==C (InstanceNorm-like) corner. Uses F.group_norm
(biased variance, divide by N) and NEVER torch.var (which defaults to
ddof=1). Self-checks the forward against a hand-derived reshape-(B,G,-1)
biased-variance reference with per-channel affine. lossGrad is randn
(non-uniform) so the dx reduction and the dgamma/dbeta sums over batch and
spatial axes are non-vacuous under mutation.

Run via `uv run` (CMake wires this automatically).
"""
import argparse
import sys
from pathlib import Path

import torch
import torch.nn.functional as F


def _format_float_literal(v: float) -> str:
    s = repr(v)
    if s in ("inf", "-inf", "nan"):
        raise ValueError(f"non-finite gold value: {v!r}")
    return s + "f"


def emit_float_array(name: str, tensor: torch.Tensor) -> str:
    flat = tensor.detach().flatten().tolist()
    body = ", ".join(_format_float_literal(v) for v in flat)
    return (
        f"static const float {name}[] = {{ {body} }};\n"
        f"static const size_t {name}_len = {len(flat)};\n"
    )


def _hand_check_forward(x, num_groups, gamma, beta, eps):
    """Biased-variance (divide by N) reference: stats over (B,G,-1) blocks
    (N = C/G * T elements each), eps inside sqrt, per-channel affine."""
    B, C, T = x.shape
    xr = x.reshape(B, num_groups, -1)
    mean = xr.mean(dim=2, keepdim=True)
    var = ((xr - mean) ** 2).mean(dim=2, keepdim=True)  # biased, ddof=0
    nhat = ((xr - mean) / torch.sqrt(var + eps)).reshape(B, C, T)
    return nhat * gamma.reshape(1, C, 1) + beta.reshape(1, C, 1)


def _run_fixture(name, B, C, T, G, *, eps=1e-5, seed=0):
    torch.manual_seed(seed)
    x = torch.randn(B, C, T, dtype=torch.float64)
    gamma = torch.randn(C, dtype=torch.float64)
    beta = torch.randn(C, dtype=torch.float64)

    x_in = x.clone().detach().requires_grad_(True)
    g_in = gamma.clone().detach().requires_grad_(True)
    b_in = beta.clone().detach().requires_grad_(True)

    y = F.group_norm(x_in, G, weight=g_in, bias=b_in, eps=eps)

    expected_y = _hand_check_forward(x_in.detach(), G, g_in.detach(),
                                     b_in.detach(), eps)
    assert torch.allclose(y.detach(), expected_y, atol=1e-9), (
        f"{name}: F.group_norm disagrees with biased-variance hand-derived"
    )

    gy = torch.randn_like(y)
    y.backward(gy)

    return {
        "name": name,
        "x": x_in.detach().to(torch.float32),
        "gamma": g_in.detach().to(torch.float32),
        "beta": b_in.detach().to(torch.float32),
        "y": y.detach().to(torch.float32),
        "dx": x_in.grad.detach().to(torch.float32),
        "dgamma": g_in.grad.detach().to(torch.float32),
        "dbeta": b_in.grad.detach().to(torch.float32),
        "gy": gy.detach().to(torch.float32),
    }


def emit_fixture(parts, fx):
    pre = f"groupNorm_{fx['name']}"
    parts.append(emit_float_array(f"input_{pre}", fx["x"]))
    parts.append(emit_float_array(f"gamma_{pre}", fx["gamma"]))
    parts.append(emit_float_array(f"beta_{pre}", fx["beta"]))
    parts.append(emit_float_array(f"expectedForward_{pre}", fx["y"]))
    parts.append(emit_float_array(f"lossGrad_{pre}", fx["gy"]))
    parts.append(emit_float_array(f"expectedPropLoss_{pre}", fx["dx"]))
    parts.append(emit_float_array(f"expectedDgamma_{pre}", fx["dgamma"]))
    parts.append(emit_float_array(f"expectedDbeta_{pre}", fx["dbeta"]))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    parts = [
        "// AUTOGENERATED by generate_expected_groupnorm.py — DO NOT EDIT\n",
        "#ifndef ODT_EXPECTED_GROUPNORM_H\n",
        "#define ODT_EXPECTED_GROUPNORM_H\n",
        "#include <stdlib.h>\n\n",
    ]

    # (name, B, C, T, G): G=1 (LayerNorm-over-[C,T]-like), G=2 (channel
    # grouping proper), batch>1 with G=3 (dgamma/dbeta sum over batch), and
    # G==C (per-channel stats, InstanceNorm-like corner).
    fixtures = [
        _run_fixture("singleGroup", 1, 4, 5, 1, seed=21),
        _run_fixture("twoGroups", 1, 8, 3, 2, seed=22),
        _run_fixture("batch2ThreeGroups", 2, 6, 4, 3, seed=23),
        _run_fixture("groupEqualsChannels", 1, 4, 3, 4, seed=24),
    ]
    for fx in fixtures:
        emit_fixture(parts, fx)

    parts.append("\n#endif // ODT_EXPECTED_GROUPNORM_H\n")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
