#!/usr/bin/env python3
"""Generate expected_bn_cadence.h for UnitTestBatchNorm1dIntegration (#460).

Ghost-BN cadence reference (#152 spec §8): one macro batch of b = 8 through
BatchNorm1d(3) -> Linear(3 -> 2) with a raw sum-of-squares loss per chunk,
split into b/m chunks of m rows, m in {2, 4, 8}. Each chunk is one
train()-mode forward+backward of the SAME module, so the running stats
update b/m times per macro batch. Emitted per m: running_mean,
running_var, num_batches_tracked, and every parameter grad times
computeMeanScaleMSE(8, [1, 2]) = 1/(8*2) (what the C side holds after
trainingBatchDefault, before the optimizer step).

Self-check: at m = 8 the scaled grads equal autograd of
F.mse_loss(lin(bn(x)), y, reduction='mean') (allclose). Literals:
repr(v)+"f". Run via `uv run` (CMake wires this automatically).
"""
import argparse

import torch
import torch.nn.functional as F

B, C, OUT = 8, 3, 2
F64 = torch.float64


def lit(v):
    s = repr(float(v))
    if s in ("inf", "-inf", "nan"):
        raise ValueError(v)
    return s + "f"


def emit(name, t):
    flat = t.detach().to(torch.float32).flatten().tolist()
    return f"static const float {name}[{len(flat)}] = {{{', '.join(lit(v) for v in flat)}}};\n"


def build(gamma, beta, w, bias):
    bn = torch.nn.BatchNorm1d(C).to(F64)
    lin = torch.nn.Linear(C, OUT).to(F64)
    with torch.no_grad():
        bn.weight.copy_(gamma)
        bn.bias.copy_(beta)
        lin.weight.copy_(w)
        lin.bias.copy_(bias)
    return bn, lin


def run(m, x, y, init):
    bn, lin = build(*init)
    bn.train()
    for k in range(0, B, m):
        out = lin(bn(x[k:k + m]))
        ((out - y[k:k + m]) ** 2).sum().backward()  # C: raw 2(o-l) grads, summed
    scale = 1.0 / (B * OUT)
    grads = [p.grad * scale for p in (bn.weight, bn.bias, lin.weight, lin.bias)]
    return bn.running_mean, bn.running_var, int(bn.num_batches_tracked), grads


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    g = torch.Generator().manual_seed(460)
    x = torch.randn(B, C, generator=g, dtype=F64)
    y = torch.randn(B, OUT, generator=g, dtype=F64)
    init = (torch.randn(C, generator=g, dtype=F64), torch.randn(C, generator=g, dtype=F64),
            torch.randn(OUT, C, generator=g, dtype=F64) * 0.5,
            torch.randn(OUT, generator=g, dtype=F64) * 0.1)
    bn, lin = build(*init)
    bn.train()
    F.mse_loss(lin(bn(x)), y, reduction="mean").backward()
    ref = [p.grad for p in (bn.weight, bn.bias, lin.weight, lin.bias)]
    _, _, _, g8 = run(8, x, y, init)
    for a, b in zip(ref, g8):
        assert torch.allclose(a, b, atol=1e-12), "m=8 chunk grads != mean-MSE autograd"
    parts = ["// AUTOGENERATED by generate_expected_bn_cadence.py -- DO NOT EDIT\n",
             "#ifndef ODT_EXPECTED_BN_CADENCE_H\n#define ODT_EXPECTED_BN_CADENCE_H\n",
             "#include <stdint.h>\n",
             emit("bnCadItems", x), emit("bnCadLabels", y), emit("bnCadGamma", init[0]),
             emit("bnCadBeta", init[1]), emit("bnCadLinW", init[2]), emit("bnCadLinB", init[3])]
    for m in (2, 4, 8):
        rm, rv, nbt, grads = run(m, x, y, init)
        parts += [emit(f"bnCadRunningMean_m{m}", rm), emit(f"bnCadRunningVar_m{m}", rv),
                  f"static const uint64_t bnCadNbt_m{m} = {nbt}u;\n",
                  emit(f"bnCadGrads_m{m}", torch.cat([t.flatten() for t in grads]))]
    parts.append("#endif\n")
    with open(args.out, "w") as f:
        f.write("".join(parts))


if __name__ == "__main__":
    main()
