#!/usr/bin/env python3
"""Generate expected_microbatch.h for UnitTestMicroBatchStacking (#152 PR3b).

One batched B=4 training step of a small conv classifier, the PyTorch
reference for trainingBatchDefault's stacked m=4 path (and its m=1 path):

    Conv1d(2->3, k=3, VALID, bias) -> ReLU -> MaxPool1d(k=2, s=2)
    -> Flatten -> Linear(9->3, bias) -> Softmax + CrossEntropy (mean)

Items are natural-shape [2, 8] samples (the loop adds the batch axis), labels
one-hot [3]. Emitted: the weights (loaded into the C layers via
layerLoadWeights), the four items and labels, the MEAN loss, and every
parameter gradient of the mean loss -- i.e. the raw per-row gradient sum
times computeMeanScaleCE(4, .) = 1/4, which is what the C side holds after
trainingBatchDefault + scaleOptimizerGradients.

Self-check: the batched autograd gradient must equal the mean of four
single-sample autograd gradients (the m=1 decomposition the C loop relies
on) -- allclose, else the build fails.

Literals: repr(v)+"f". Run via `uv run` (CMake wires this automatically).
"""
import argparse

import torch
import torch.nn.functional as F

B, C_IN, L_IN, C_OUT, K, N_CLS = 4, 2, 8, 3, 3, 3
POOL = 2
FLAT = C_OUT * ((L_IN - K + 1) // POOL)  # 3 * 3 = 9
LABEL_CLASSES = [0, 2, 1, 2]


def lit(v: float) -> str:
    s = repr(float(v))
    if s in ("inf", "-inf", "nan"):
        raise ValueError(f"non-finite gold value: {v!r}")
    return s + "f"


def emit(name: str, t: torch.Tensor) -> str:
    flat = t.detach().flatten().tolist()
    body = ", ".join(lit(v) for v in flat)
    return f"static const float {name}[{len(flat)}] = {{{body}}};\n"


def forward(x, cw, cb, lw, lb):
    h = F.conv1d(x, cw, cb)
    h = F.relu(h)
    h = F.max_pool1d(h, kernel_size=POOL, stride=POOL)
    h = h.flatten(start_dim=1)
    return F.linear(h, lw, lb)


def mean_ce(logits, y):
    # C side: sum(y * -log(softmax)) / rows (crossEntropyForwardFloat's
    # MEAN rule).
    return -(y * torch.log_softmax(logits, dim=1)).sum() / logits.shape[0]


def grads(x, y, params):
    for p in params:
        p.grad = None
    loss = mean_ce(forward(x, *params), y)
    loss.backward()
    return loss.detach(), [p.grad.detach().clone() for p in params]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    g = torch.Generator().manual_seed(152)
    x = torch.randn(B, C_IN, L_IN, generator=g, dtype=torch.float32)
    cw = (torch.randn(C_OUT, C_IN, K, generator=g) * 0.4).requires_grad_()
    cb = (torch.randn(C_OUT, generator=g) * 0.1).requires_grad_()
    lw = (torch.randn(N_CLS, FLAT, generator=g) * 0.3).requires_grad_()
    lb = (torch.randn(N_CLS, generator=g) * 0.1).requires_grad_()
    params = [cw, cb, lw, lb]
    y = F.one_hot(torch.tensor(LABEL_CLASSES), N_CLS).to(torch.float32)

    loss, batched = grads(x, y, params)

    # Self-check: batched mean-loss grad == mean of per-sample grads.
    per_sample = [grads(x[i : i + 1], y[i : i + 1], params)[1] for i in range(B)]
    for j, gb in enumerate(batched):
        ref = torch.stack([ps[j] for ps in per_sample]).mean(dim=0)
        assert torch.allclose(gb, ref, rtol=1e-5, atol=1e-7), f"param {j} self-check failed"

    out = [
        "/* Generated by generate_expected_microbatch.py -- do not edit. */\n",
        "#ifndef EXPECTED_MICROBATCH_H\n#define EXPECTED_MICROBATCH_H\n\n",
        f"#define MB_GOLD_B {B}\n#define MB_GOLD_C_IN {C_IN}\n#define MB_GOLD_L_IN {L_IN}\n",
        f"#define MB_GOLD_C_OUT {C_OUT}\n#define MB_GOLD_K {K}\n#define MB_GOLD_CLASSES {N_CLS}\n",
        f"#define MB_GOLD_FLAT {FLAT}\n\n",
        emit("mbGoldConvW", cw),
        emit("mbGoldConvB", cb),
        emit("mbGoldLinW", lw),
        emit("mbGoldLinB", lb),
        emit("mbGoldItems", x),
        emit("mbGoldLabels", y),
        f"static const float mbGoldLoss = {lit(loss.item())};\n",
        emit("mbGoldConvWGrad", batched[0]),
        emit("mbGoldConvBGrad", batched[1]),
        emit("mbGoldLinWGrad", batched[2]),
        emit("mbGoldLinBGrad", batched[3]),
        "\n#endif /* EXPECTED_MICROBATCH_H */\n",
    ]
    with open(args.out, "w") as f:
        f.write("".join(out))


if __name__ == "__main__":
    main()
